version: '3.7'
 
services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
  userapp:
    depends_on: 
      - "db"
    build: .
    ports:
      - "5598:80"
volumes: 
  db:
    